#!/bin/bash

function aws_execute()
{
	exec $@
	[ $? -eq 0 ] && return 1 || return 0
}

kali_instance="i-0d9868b9e4c2f7ccc"

aws_execute aws ec2 start-instances --instance-id ${kali_instance} --region us-east-1
aws_execute aws ec2 wait instance-running --instance-id ${kali_instance} --region us-east-1

